import type { Metadata } from 'next';
import { Check, ExternalLink, Info } from 'lucide-react';
import { SHOP_SITE_URL } from '@/lib/shop';

export const metadata: Metadata = { title: 'How it works', description: 'How Auronix Select curates products and uses Amazon affiliate links.', alternates: { canonical: `${SHOP_SITE_URL}/about` } };

export default function ShopAboutPage() {
  return <div className="mx-auto max-w-4xl px-5 py-20 sm:px-6 lg:py-28"><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-600">Transparency</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.05em] sm:text-7xl">How Auronix Select works.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-zinc-500">We publish a deliberately small catalog and direct visitors to Amazon to review the current product offer.</p><div className="mt-14 grid gap-5 md:grid-cols-3">{[{icon: Check,title:'Focused fields',body:'We show stable identifying information such as brand, product family, model, size, or capacity.'},{icon: Info,title:'No commercial guesses',body:'We do not copy or invent ratings, reviews, prices, discounts, stock status, or seller claims.'},{icon: ExternalLink,title:'Verify on Amazon',body:'Amazon is the source for the live offer, seller, delivery, returns, availability, and current terms.'}].map(({icon: Icon,title,body}) => <section key={title} className="rounded-[2rem] border border-black/[.07] bg-white p-7 dark:border-white/10 dark:bg-zinc-950"><Icon className="h-5 w-5 text-blue-600" /><h2 className="mt-6 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{body}</p></section>)}</div><section className="mt-12 rounded-[2rem] bg-zinc-950 p-8 text-white sm:p-10"><h2 className="text-2xl font-semibold">Amazon Associates disclosure</h2><p className="mt-4 leading-7 text-zinc-300">As an Amazon Associate, Auronix Commerce earns from qualifying purchases. When you follow an affiliate link and make a qualifying purchase, Auronix Commerce may receive a commission. This does not make Amazon the seller of content on this site, nor does it make Auronix Commerce the seller of the linked product.</p></section></div>;
}
